### ISSUE TITLE
Inconsistency(?) in loading packages

### ISSUE THREAD

**Issue by gcapes** [UoMResearchIT/r-tidyverse-digital-humanities#11]
It's not clear to me if/why/when `library(tidyverse)` should be used instead of `library("tidyverse")`. There are other examples of libraries loaded using both methods.

**Comment by mawds** [comment]
I use both methods myself, without giving it much thought 

https://stackoverflow.com/questions/36802132/the-use-of-quotation-marks-when-loading-a-package-in-r 
suggests quotes are preferable, for sensible reasons
